/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Concentration",
  primary: "#EC4899",
  secondary: "#9D174D",
  splash: {
    glow: "rgba(157,23,77,0.6)",
    sallyGlow: "rgba(236,72,153,0.8)",
    pillBorder: "rgba(236,72,153,0.5)",
    pillBg: "rgba(157,23,77,0.15)",
    pillText: "#FBCFE8",
    suit: "✧",
    suit2: "◍",
  },
  slides: {
    slide2: { tint: ["rgba(236,72,153,0.55)","rgba(157,23,77,0.7)","rgba(40,8,28,0.95)"], variant: "scattered" },
    slide3: { tint: ["rgba(244,114,182,0.45)","rgba(131,24,67,0.85)","rgba(40,8,28,0.95)"], variant: "grid" },
    slide4: { tint: ["rgba(168,85,247,0.45)","rgba(236,72,153,0.7)","rgba(40,8,28,0.95)"], variant: "fan" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
